### ISSUE TITLE
Crashes when switching boards.

### ISSUE THREAD

**Issue by michaelckchow** [hjohnson12/Kanban-Tasker#55]
App crashes when switching boards. Running Win11 and KT1.3.5.

**Comment by michaelckchow** [comment]
I have managed to solve this by deleting and recreating the boards. Not the most ideal solution though.

**Comment by mediaexplorer74** [comment]
michaelckchow),

 Not the most ideal solution, indeed.  Kanban-Tasker is open source. IMHO, more good solition to fix crashes when switching boards... if you are engeneer.
