### ISSUE TITLE
Sort tasks by priority

### ISSUE THREAD

**Issue by romgerman** [hjohnson12/Kanban-Tasker#7]
Can we have it?

**Comment by hjohnson12** [comment]
Hey @romgerman ! I'm so sorry for the late response, I never saw the notification for this! 

Regarding sorting the tasks by priority, this is on my list of to-do's for Kanban and hope to add it into a future update after I can alter users current databases without data loss. Feel free to check-in on my branches on the repo every now and then for latest changes :) 

Best Regards, 
Hunter
