### ISSUE TITLE
App crashes when trying to create a new board

### ISSUE THREAD

**Issue by sagarthomas** [hjohnson12/Kanban-Tasker#8]
Just installed it from the store and when I try to make a new board, the app immediately closes.

Seen on version 1.0.4.0 

I'm running this on Windows 10 Home 1903 build 18362.418 (64-bit) if it helps.

**Comment by hjohnson12** [comment]
Hi Sagarthomas! 

Thank you for your bug report! I fixed and pushed version 1.0.5.0 to the store last night which should fix that issue :)
